insert into public.yas_site_content (key,en,ar) values
('brand.name','YAS Holding','يس القابضة'),
('brand.tagline','Crafting Excellence','نصنع التميّز'),
('nav.home','Home','الرئيسية'),
('nav.about','About','من نحن'),
('nav.brands','Brands','علاماتنا'),
('nav.careers','Careers','الوظائف'),
('nav.contact','Contact','تواصل معنا'),
('cta.explore','Explore our brands','استكشف علاماتنا'),
('cta.contact','Get in touch','تواصل معنا'),
('cta.learnmore','Learn more','اعرف المزيد'),
('home.hero.eyebrow','Bahrain-based group · Est. 2012','مجموعة بحرينية · تأسست 2012'),
('home.hero.title','A holding company built on craft.','شركة قابضة قامت على الحرفة.'),
('home.hero.subtitle','YAS Holding brings together premium wood manufacturing and custom furniture craftsmanship under one group — delivering excellence to clients across 15 countries.','تجمع يس القابضة بين تصنيع الأخشاب الفاخرة وحرفية الأثاث المُصمّم خصيصاً تحت مظلة واحدة — نقدّم التميّز لعملائنا في 15 دولة.'),
('home.stat1.n','2012','2012'),
('home.stat1.l','Established','سنة التأسيس'),
('home.stat2.n','15+','+15'),
('home.stat2.l','Countries served','دولة نخدمها'),
('home.stat3.n','200+','+200'),
('home.stat4.n','ISO 9001','أيزو 9001'),
('home.stat3.l','People across the group','موظف في المجموعة'),
('home.stat4.l','Quality certified','معتمدون للجودة'),
('home.subs.eyebrow','Our subsidiaries','شركاتنا'),
('home.subs.title','Two brands, one standard.','علامتان، ومعيار واحد.'),
('home.subs.sub','Each company in the group is a specialist in its field, united by a shared commitment to quality, sustainability and craftsmanship.','كل شركة في المجموعة متخصصة في مجالها، تجمعنا التزام مشترك بالجودة والاستدامة والحرفية.'),
('home.commit.eyebrow','Our commitment','التزامنا'),
('home.commit.title','The principles behind every piece.','المبادئ خلف كل قطعة.'),
('home.commit.1.t','Sustainable','الاستدامة'),
('home.commit.1.d','Responsibly sourced materials and eco-conscious processes for a better tomorrow.','مواد من مصادر مسؤولة وعمليات صديقة للبيئة من أجل غدٍ أفضل.'),
('home.commit.2.t','Custom Design','التصميم المخصّص'),
('home.commit.2.d','Tailored solutions engineered to fit each client, space and specification.','حلول مصمّمة خصيصاً لتناسب كل عميل ومساحة ومواصفات.'),
('home.commit.3.t','Quality Craftsmanship','حرفية الجودة'),
('home.commit.3.d','ISO 9001:2015 processes and expert artisans behind every finished product.','عمليات مطابقة لأيزو 9001:2015 وحرفيون خبراء خلف كل منتج.'),
('home.band.title','One group. End-to-end capability.','مجموعة واحدة. قدرة متكاملة.'),
('home.band.sub','From raw material to finished, installed furniture — the YAS Holding group owns the full value chain.','من المادة الخام إلى الأثاث المُركّب — تمتلك مجموعة يس القابضة سلسلة القيمة الكاملة.'),
('about.hero.eyebrow','About the group','عن المجموعة'),
('about.hero.title','Excellence, from forest to finish.','التميّز، من الغابة إلى التشطيب.'),
('about.hero.sub','Founded in 2012 and headquartered in the Kingdom of Bahrain, YAS Holding is a family of specialist companies in wood and furniture manufacturing.','تأسست عام 2012 ومقرها مملكة البحرين، يس القابضة عائلة من الشركات المتخصصة في تصنيع الأخشاب والأثاث.'),
('about.story.title','Our story','قصتنا'),
('about.story.p1','YAS Holding began with a simple conviction: that standardised processes, regulatory compliance and genuine craftsmanship are the cornerstones of lasting success. From a single wood factory in Bahrain, the group has grown into a multi-company operation serving clients across the Gulf and beyond.','بدأت يس القابضة بقناعة بسيطة: أن العمليات المُوحّدة والامتثال التنظيمي والحرفية الحقيقية هي أسس النجاح الدائم. من مصنع أخشاب واحد في البحرين، نمت المجموعة إلى عملية متعددة الشركات تخدم العملاء في الخليج وخارجه.'),
('about.story.p2','Today, through YAS Wood and The Closets International, we design, manufacture, deliver and install — owning the full value chain and holding every stage to the same exacting standard.','اليوم، من خلال يس وود وذا كلوزتس إنترناشونال، نصمّم ونصنّع ونسلّم ونركّب — نمتلك سلسلة القيمة الكاملة ونحافظ على المعيار نفسه في كل مرحلة.'),
('about.mv.mission.t','Mission','رسالتنا'),
('about.mv.mission.d','To deliver high-quality wood and furniture products through standardised, compliant and efficient processes that earn the trust of our clients and partners.','تقديم منتجات أخشاب وأثاث عالية الجودة عبر عمليات موحّدة ومتوافقة وفعّالة تكسب ثقة عملائنا وشركائنا.'),
('about.mv.vision.t','Vision','رؤيتنا'),
('about.mv.vision.d','To be the region’s benchmark group for premium wood and bespoke furniture — recognised for craftsmanship, reliability and responsible growth.','أن نكون المجموعة المرجعية في المنطقة للأخشاب الفاخرة والأثاث المُصمّم — معروفين بالحرفية والموثوقية والنمو المسؤول.'),
('about.values.title','What we stand for','ما نؤمن به'),
('about.iso.eyebrow','Quality management','إدارة الجودة'),
('about.iso.title','ISO 9001:2015 certified.','معتمدون وفق أيزو 9001:2015.'),
('about.iso.p','Our operations are governed by documented policies, key responsibility areas and measurable performance indicators. Standardised work instructions, forms and flowcharts ensure every task is performed consistently — from a sales enquiry to final delivery.','تُدار عملياتنا بسياسات موثّقة ومجالات مسؤولية رئيسية ومؤشرات أداء قابلة للقياس. تضمن تعليمات العمل والنماذج والمخططات الموحّدة أداء كل مهمة باتساق — من الاستفسار البيعي إلى التسليم النهائي.'),
('about.leader.eyebrow','Leadership','القيادة'),
('about.leader.name','Ali Alhaddad','علي الحداد'),
('about.leader.role','Managing Director','العضو المنتدب'),
('about.leader.quote','“We build companies the way we build furniture — measured, honest and made to last.”','«نبني الشركات كما نصنع الأثاث — بدقّة وصدق وصُنعٍ يدوم.»'),
('ywood.hero.eyebrow','A YAS Holding company','شركة من يس القابضة'),
('ywood.hero.title','YAS Wood','يس وود'),
('ywood.hero.sub','Premium wood materials and manufacturing — supplying the region with quality panels, boards and bespoke joinery, produced to ISO 9001:2015 standards.','مواد أخشاب فاخرة وتصنيع — نزوّد المنطقة بألواح وأخشاب ونجارة مخصّصة عالية الجودة، مُنتجة وفق معايير أيزو 9001:2015.'),
('ywood.body.title','Manufacturing, standardised.','تصنيع مُوحّد المعايير.'),
('ywood.body.p','YAS Wood operates a dedicated factory in Bahrain, producing melamine panels, boards, wood samples and custom orders for local and international clients. Every order flows through a documented process — from quotation and sales order to production, dispatch and delivery — tracked end to end.','تدير يس وود مصنعاً مخصصاً في البحرين، لإنتاج ألواح الميلامين والأخشاب وعيّنات الخشب والطلبات المخصّصة للعملاء المحليين والدوليين. يمرّ كل طلب عبر عملية موثّقة — من عرض السعر وأمر البيع إلى الإنتاج والشحن والتسليم — بتتبّع كامل.'),
('ywood.f1.t','Panels & boards','الألواح والأخشاب'),
('ywood.f1.d','Melamine panels and engineered boards in a wide range of colours and finishes.','ألواح ميلامين وأخشاب هندسية بمجموعة واسعة من الألوان والتشطيبات.'),
('ywood.f2.t','Bespoke joinery','نجارة مخصّصة'),
('ywood.f2.d','Made-to-order components manufactured to precise client specifications.','مكوّنات تُصنع حسب الطلب وفق مواصفات دقيقة للعميل.'),
('ywood.f3.t','Export-ready','جاهز للتصدير'),
('ywood.f3.d','CFR and door-to-door delivery with full export documentation.','تسليم CFR ومن الباب إلى الباب مع وثائق تصدير كاملة.'),
('closets.hero.eyebrow','A YAS Holding company','شركة من يس القابضة'),
('closets.hero.title','The Closets International','ذا كلوزتس إنترناشونال'),
('closets.hero.sub','One of the region’s leading closets and kitchens manufacturers — bespoke wardrobes, kitchens and storage, designed, built and installed across Bahrain, Saudi Arabia and the UAE.','أحد أبرز مصنّعي الخزائن والمطابخ في المنطقة — خزائن ومطابخ وحلول تخزين مخصّصة، تُصمّم وتُصنّع وتُركّب في البحرين والسعودية والإمارات.'),
('closets.body.title','Bespoke furniture, at scale.','أثاث مخصّص، على نطاق واسع.'),
('closets.body.p','With a team of more than 200 across the Gulf, The Closets International brings the group’s craftsmanship directly to homes — from free design consultations and 3D planning to in-house manufacturing and professional installation.','بفريق يزيد عن 200 شخص في الخليج، تنقل ذا كلوزتس إنترناشونال حرفية المجموعة مباشرة إلى المنازل — من استشارات التصميم المجانية والتخطيط ثلاثي الأبعاد إلى التصنيع الداخلي والتركيب الاحترافي.'),
('closets.cta','Visit The Closets website','زر موقع ذا كلوزتس'),
('careers.hero.eyebrow','Careers','الوظائف'),
('careers.hero.title','Build your career with the group.','ابنِ مسيرتك مع المجموعة.'),
('careers.hero.sub','We’re always looking for people who take pride in doing things properly. Explore open roles across YAS Holding and its companies.','نبحث دائماً عن أشخاص يفخرون بإتقان العمل. استكشف الوظائف المتاحة في يس القابضة وشركاتها.'),
('careers.open.title','Open positions','الوظائف المتاحة'),
('careers.empty','No open positions right now — but we’d still like to hear from you. Send your CV to careers@yas-holding.com.','لا توجد وظائف متاحة حالياً — لكن يسعدنا أن نسمع منك. أرسل سيرتك إلى careers@yas-holding.com.'),
('careers.apply','Apply','تقديم'),
('contact.hero.eyebrow','Contact','تواصل معنا'),
('contact.hero.title','Let’s talk.','لنتحدّث.'),
('contact.hero.sub','Whether you’re a client, partner or supplier, our team is here to help.','سواء كنت عميلاً أو شريكاً أو مورّداً، فريقنا هنا لمساعدتك.'),
('contact.info.title','Head office','المكتب الرئيسي'),
('contact.addr.k','Address','العنوان'),
('contact.addr.v','Road 5136, Building 1338G, Askar, Kingdom of Bahrain','طريق 5136، مبنى 1338G، عسكر، مملكة البحرين'),
('contact.phone.k','Phone','الهاتف'),
('contact.email.k','Email','البريد الإلكتروني'),
('contact.hours.k','Hours','ساعات العمل'),
('contact.hours.v','Sunday – Thursday, 8:00am – 5:00pm','الأحد – الخميس، 8:00ص – 5:00م'),
('contact.form.title','Send us a message','أرسل لنا رسالة'),
('contact.form.name','Full name','الاسم الكامل'),
('contact.form.email','Email','البريد الإلكتروني'),
('contact.form.phone','Phone','الهاتف'),
('contact.form.subject','Subject','الموضوع'),
('contact.form.message','Message','الرسالة'),
('contact.form.send','Send message','إرسال'),
('contact.form.sending','Sending…','جارٍ الإرسال…'),
('contact.form.ok','Thank you — your message has been received. We’ll be in touch shortly.','شكراً لك — تم استلام رسالتك وسنتواصل معك قريباً.'),
('contact.form.err','Sorry, something went wrong. Please try again or email us directly.','عذراً، حدث خطأ ما. حاول مجدداً أو راسلنا مباشرة.'),
('footer.blurb','A Bahrain-based group crafting excellence in premium wood and custom furniture through its specialist companies.','مجموعة بحرينية تصنع التميّز في الأخشاب الفاخرة والأثاث المخصّص من خلال شركاتها المتخصصة.'),
('footer.quick','Quick links','روابط سريعة'),
('footer.brands','Our brands','علاماتنا'),
('footer.contact','Contact','تواصل'),
('footer.rights','© 2026 YAS Holding. All rights reserved.','© 2026 يس القابضة. جميع الحقوق محفوظة.')
on conflict (key) do update set en=excluded.en, ar=excluded.ar, updated_at=now();
